In [21]:
%pip install transformers ipywidgets huggingface_hub torch accelerate

Requirement already satisfied: transformers in ./envs/lib/python3.13/site-packages (4.57.6)
Requirement already satisfied: ipywidgets in ./envs/lib/python3.13/site-packages (8.1.8)
Requirement already satisfied: huggingface_hub in ./envs/lib/python3.13/site-packages (0.36.0)
Requirement already satisfied: torch in ./envs/lib/python3.13/site-packages (2.10.0)
Requirement already satisfied: accelerate in ./envs/lib/python3.13/site-packages (1.12.0)
Requirement already satisfied: filelock in ./envs/lib/python3.13/site-packages (from transformers) (3.20.3)
Requirement already satisfied: numpy>=1.17 in ./envs/lib/python3.13/site-packages (from transformers) (2.4.1)
Requirement already satisfied: packaging>=20.0 in ./envs/lib/python3.13/site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in ./envs/lib/python3.13/site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in ./envs/lib/python3.13/site-packages (from transformers) (2026.1.15)
Requirement already satisfied: requests in ./envs/lib/python3.13/site-packages (from transformers) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in ./envs/lib/python3.13/site-packages (from transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in ./envs/lib/python3.13/site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in ./envs/lib/python3.13/site-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in ./envs/lib/python3.13/site-packages (from huggingface_hub) (2026.1.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in ./envs/lib/python3.13/site-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in ./envs/lib/python3.13/site-packages (from huggingface_hub) (1.2.0)
Requirement already satisfied: comm>=0.1.3 in ./envs/lib/python3.13/site-packages (from ipywidgets) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in ./envs/lib/python3.13/site-packages (from ipywidgets) (9.7.0)
Requirement already satisfied: traitlets>=4.3.1 in ./envs/lib/python3.13/site-packages (from ipywidgets) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in ./envs/lib/python3.13/site-packages (from ipywidgets) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in ./envs/lib/python3.13/site-packages (from ipywidgets) (3.0.16)
Requirement already satisfied: setuptools in ./envs/lib/python3.13/site-packages (from torch) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in ./envs/lib/python3.13/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in ./envs/lib/python3.13/site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in ./envs/lib/python3.13/site-packages (from torch) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in ./envs/lib/python3.13/site-packages (from torch) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in ./envs/lib/python3.13/site-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in ./envs/lib/python3.13/site-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in ./envs/lib/python3.13/site-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in ./envs/lib/python3.13/site-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in ./envs/lib/python3.13/site-packages (from torch) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in ./envs/lib/python3.13/site-packages (from torch) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in ./envs/lib/python3.13/site-packages (from torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in ./envs/lib/python3.13/site-packages (from torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in ./envs/lib/python3.13/site-packages (from torch) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in ./envs/lib/python3.13/site-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in ./envs/lib/python3.13/site-packages (from torch) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in ./envs/lib/python3.13/site-packages (from torch) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in ./envs/lib/python3.13/site-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in ./envs/lib/python3.13/site-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in ./envs/lib/python3.13/site-packages (from torch) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in ./envs/lib/python3.13/site-packages (from torch) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in ./envs/lib/python3.13/site-packages (from cuda-bindings==12.9.4->torch) (1.3.3)
Requirement already satisfied: psutil in ./envs/lib/python3.13/site-packages (from accelerate) (7.0.0)
Requirement already satisfied: decorator>=4.3.2 in ./envs/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in ./envs/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in ./envs/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.5 in ./envs/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets) (0.2.1)
Requirement already satisfied: pexpect>4.3 in ./envs/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in ./envs/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in ./envs/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in ./envs/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: wcwidth in ./envs/lib/python3.13/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.2.14)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in ./envs/lib/python3.13/site-packages (from jedi>=0.18.1->ipython>=6.1.0->ipywidgets) (0.8.5)
Requirement already satisfied: ptyprocess>=0.5 in ./envs/lib/python3.13/site-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets) (0.7.0)
Requirement already satisfied: executing>=1.2.0 in ./envs/lib/python3.13/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in ./envs/lib/python3.13/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (3.0.0)
Requirement already satisfied: pure_eval in ./envs/lib/python3.13/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (0.2.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in ./envs/lib/python3.13/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./envs/lib/python3.13/site-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in ./envs/lib/python3.13/site-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in ./envs/lib/python3.13/site-packages (from requests->transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./envs/lib/python3.13/site-packages (from requests->transformers) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in ./envs/lib/python3.13/site-packages (from requests->transformers) (2026.1.4)
Note: you may need to restart the kernel to use updated packages.

In [22]:
import torch
assert torch.cuda.is_available()
torch.set_default_device('cuda')

To download the model you must login to hugging face and request access to the [repository](https://huggingface.co/meta-llama/Llama-3.2-1B-Instruct/tree/main). They may take some time to approve the request, you can check the state [here](https://huggingface.co/settings/gated-repos). Note: if you have been granted access to another Llama model then you should already have access.

Then you will need to create a [hugging face access token](https://huggingface.co/settings/tokens), granting it the "Read access to contents of all public gated repos you can access" permission. Then run the cell below and input the token there.

In [23]:
from huggingface_hub import notebook_login
notebook_login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [24]:
import pandas as pd

PLACE_COLS = [
    "ApplicantBirthPlace", 
    "ApplicantCurrentAddress", 
    "VictimBirthPlace", 
    "VictimDeathPlace",
    "VictimCurrentAddress"
]

df = pd.read_json("data/1870.json")

print(f"Number of BZK cards: {len(df)}")

sampled = df.sample(n=10)
sampled.sample(n=10)

Number of BZK cards: 1335

,CompensationOffice1,BZKNr,ApplicantFirstName,ApplicantLastName,ApplicantAltFirstName,ApplicantBirthName,ApplicantAltLastName,ApplicantBirthDate,ApplicantBirthPlace,ApplicantCurrentAddress,...,VictimBirthDate,VictimBirthPlace,VictimDeathDate,VictimDeathPlace,VictimCurrentAddress,Heirs,full_response,path,filename,model_name
426,Der Regierungspräsident Dezernat für Wiedergut...,439 011,Emma,Löwenstein,None,Grünwald,None,3.5.1870,Alhausen b. Driburg,Philadelphia 4330 'M' Street,...,None,None,None,None,None,None,"```python\n{\n ""CompensationOffice1"": ""Der ...",/home/bzk-data/1870/,1870_05_03_2_0.jpg,InternvlLmdeployModel_InternVL2_5-38B_p-9_fews...
159,Hess. Staatsministerium,02971,,,,,,,,,...,17.2.1970,Berlin,,,"Wiesbaden, Hollnundstr.6",,"```python\n{\n ""CompensationOffice1"": ""Hess...",/home/bzk-data/1870/,1870_02_17_1_0.jpg,InternvlLmdeployModel_InternVL2_5-38B_p-9_fews...
5,None,29 584/I/7523,None,None,None,None,None,None,None,None,...,2.3. 70,Esseck,None,None,München - Solln Wolfrathausenstr. 214,None,"```python\n{\n ""CompensationOffice1"": None,...",/home/bzk-data/1870/,1870_03_02_2_0.jpg,InternvlLmdeployModel_InternVL2_5-38B_p-9_fews...
1142,Bezirksamt für Wiedergutmachung Trier,262606,Essia,Muchnik,None,Krutiansky,None,6.4.1870,Odessa/Russl.,"43 W 93 St., c/o Mitchell, New York/USA",...,1904,None,None,Anfang 1942 von Paris nach Auschwitz deportier...,None,None,"```python\n{\n ""CompensationOffice1"": ""Bezi...",/home/bzk-data/1870/,1870_04_06_4_0.jpg,InternvlLmdeployModel_InternVL2_5-38B_p-9_fews...
237,Bayerisches Landesentschädigungsamt,BEG 19359,Eduard,Lindenthal,None,None,None,18.1.1870,Galveston / USA,"Belgrano 302, Buenos Aires, Argentinien",...,None,None,None,None,None,EG AZ.: 96199/129734,"```python\n{\n ""CompensationOffice1"": ""Baye...",/home/bzk-data/1870/,1870_01_18_3_0.jpg,InternvlLmdeployModel_InternVL2_5-38B_p-9_fews...
578,Niedersachsen,233 964,Maria,Zuker,None,Silberstein,None,1.5.1870,Kallern/Schweiz,"Buenos Aires/Argentinien, Las Heras 2928",...,None,None,None,None,None,None,"```python\n{\n ""CompensationOffice1"": ""Nied...",/home/bzk-data/1870/,1870_05_01_8_0.jpg,InternvlLmdeployModel_InternVL2_5-38B_p-9_fews...
174,Arnsberg,28 939 a,Cäcilie,Jochim,None,Nikoleiski,None,10.3.70,Dirschau/Wpr.,"Schwerde/Kreis Iserlohn, Lohbachstr. 27",...,None,None,30.3.49,Schwerde/Krs. Iserlohn,None,None,"```python\n{\n ""CompensationOffice1"": ""Arns...",/home/bzk-data/1870/,1870_03_10_3_0.jpg,InternvlLmdeployModel_InternVL2_5-38B_p-9_fews...
959,Freiburg/Br.,10730,Ottilie,Köehler,None,Wömer,None,25.4.1870,Asbach,"Freiburg/Br., Catharinenstift am Stadttgarten",...,14.11.1870,Hamburg,9.3.1947,Freiburg/Br.,None,"Erbchein liegt hier, noch nicht vpr.","```python\n{\n ""CompensationOffice1"": ""Frei...",/home/bzk-data/1870/,1870_04_25_2_0.jpg,InternvlLmdeployModel_InternVL2_5-38B_p-9_fews...
801,Bezirksamt für Wiedergutmachung Koblenz,367172,Roman,Stoleru,None,Roman,None,21.6.1870,Israel Bet Dagon Str. Gimmel 14,Fonfe Koblenz,...,1865,None,None,None,None,None,"```python\n{\n ""CompensationOffice1"": ""Bezi...",/home/bzk-data/1870/,1870_06_21_4_0.jpg,InternvlLmdeployModel_InternVL2_5-38B_p-9_fews...
807,"Landesamt für die Wiedergutmachung, Karlsruhe",EK 12 101 / A,Jenny,Weil,None,Kirchheimer,None,11.4.1870,Beerwangen/Baden,"Avda. de los Incas 3350, Buenos Aires/Argt.",...,26.8.1859,Steinsfurt,15.11.1931,Steinsfurt,None,[Jenny Weil,"```python\n{\n ""CompensationOffice1"": ""Land...",/home/bzk-data/1870/,1870_04_11_4_0.jpg,InternvlLmdeployModel_InternVL2_5-38B_p-9_fews...

In [43]:
from unittest import result
from transformers import pipeline
import json



PROMPTS = [
    "Segment the following address into components: {address}\n"
    "Output only a JSON object with the following keys: streetNumber, street, city, state, country, "
    "postcode, houseNumber, buildingName. "
    "You can add new keys but only if a component does not fit one of the given keys. "
    "Do not set any value that is not explicitly present in the address, "
    "fill fields that cannot be determined with null. "
    "Addresses may include german terms such as 'Straße' for street or its abbreviation 'Str.'. "
    "These may occur as a suffix to the street name.",

    "Annotate each component in the following address: {address}\n"
    "Consider the component types streetNumber, street, city, state, country, "
    "postcode, houseNumber, buildingName. "
    "You can add new types but only if a component does not fit one of the given types. "
    "Each component type should only occur once in each address. Not all addresses will contain all component types and you should not add the missing ones. "
    "Note that addresses may include german terms such as 'Straße' for street or its abbreviation 'Str.'. "
    "These may occur as a suffix to the street name. "
    "Output only a JSON list of [component, type] tuples. For example, the address \"Berlin, Alexanderplatz 1, 10178\" should be annotated as:\n"
    "```json\n[ [\"Berlin\", \"city\"], [\"Alexanderplatz\", \"street\"], [\"1\", \"streetNumber\"], [\"10178\", \"postcode\"] ]\n```"
    
]

class LlamaAddressSegmentationModel:
    def __init__(self, model_name, prompt, output_parser = None):
        self.pipe = pipeline("text-generation", model=model_name)
        self.prompt = prompt
        self.output_parser = output_parser or (lambda x : x)

    def segment_address(self, address: str) -> str:
        messages = [
            {"role": "user", "content": self.prompt.format(address=address)}
        ]
        result = self.pipe(messages)
        response = result[0]["generated_text"][1]["content"]
        return self.output_parser(response)

def extract_json_block(model_response : str):
    limit_chars = [('{', '}'), ('[', ']'), ('"', '"')]
    json_str = model_response
    parts = model_response.split("```")
    if len(parts) == 3:
        json_str = parts[1]
    elif len(parts) >= 3:
        for part in parts:
            part = part.strip()
            if part.startswith("json") or any(part.startswith(lim[0]) and part.endswith(lim[1]) for lim in limit_chars):
                json_str = part
                break
    if json_str.startswith("json"):
        json_str = json_str[4:].strip()
    return json_str

class JSONbjectParser:
    def __call__(self, response: str) -> dict:
        try:
            json_str = extract_json_block(response)
            obj = json.loads(json_str)
            for k in obj.keys():
                assert k not in ["fullResponse", "model-fullAddress", "parseError"], f"Key collision with reserved field: {k}"
                # It is plausible that the model just echoes back the full address in a field named "fullAddress"
                # But that would collide with our own field named "fullAddress" that we add later
                if k == "fullAddress":
                    obj["model-fullAddress"] = obj["fullAddress"] # avoid collision but keep the wrongfully generated field
            obj["fullResponse"] = response
            data = obj
        except json.JSONDecodeError as e:
            data = {"fullResponse": response, "parseError": f"JSONDecodeError: {e}"}
        return data

class JSONTuplesParser:
    def __call__(self, response: str) -> dict:
        try:
            json_str = extract_json_block(response)
            tuples = json.loads(json_str)
            data = {}
            for part, ptype in tuples:
                if isinstance(part, str) and part.strip() == "":
                    continue
                assert ptype not in ["fullResponse", "model-fullAddress", "parseError"], f"Key collision with reserved field: {ptype}"
                if ptype == "fullAddress":
                    data["model-fullAddress"] = data["fullAddress"] # avoid collision but keep the wrongfully generated field
                else:
                    collision_value = data.get(ptype)
                    if collision_value is None:
                        data[ptype] = part
                    else:
                        data[ptype] = collision_value + "___" + part
            data["fullResponse"] = response
        except json.JSONDecodeError as e:
            data = {"fullResponse": response, "parseError": f"JSONDecodeError: {e}"}
        return data

In [31]:
from collections import OrderedDict
sample_addresses = df[PLACE_COLS].stack().sample(n=5, random_state=26012026)

def test_model(model, addresses=sample_addresses):
    # Ordered set of all keys seen in results (values don't matter, but there is no collection ordered set)
    col_names = OrderedDict((k, 0) for k in [
        "fullAddress", "fullResponse", "streetNumber", "street", "city", "state", "country", 
        "postcode", "houseNumber", "buildingName"]) 
    rows = []
    for (rid, field), address in addresses.items():
        print(f"Record ID: {rid} / Field: {field} / Address: {address}")
        response = model.segment_address(address)
        for k in response.keys(): 
            col_names[k] = 0  # add any new keys to the ordered set (again, value doesn't matter)
        response["fullAddress"] = address
        print(f"Parsed response: {response}")
        rows.append(response)
    return pd.DataFrame(rows, index=addresses.index, columns=col_names.keys())

In [ ]:
model = LlamaAddressSegmentationModel("meta-llama/Llama-3.2-1B-Instruct", PROMPTS[0], JSONbjectParser())
test_model(model).dropna(how="all", axis=1).fillna("")

Device set to use cuda:0
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Record ID: 702 / Field: VictimCurrentAddress / Address: Kriftel, Bahnhofstr. 15

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Record ID: 1220 / Field: ApplicantCurrentAddress / Address: 89-04 th Avenue, Jackson Heights L.I. N.Y./USA

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Record ID: 39 / Field: ApplicantCurrentAddress / Address: Nathania, Nordaustr. 34, Israel c/o Moskowitz Mosche

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Record ID: 1266 / Field: ApplicantBirthPlace / Address: Budapest/Ungarn

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Record ID: 1292 / Field: ApplicantCurrentAddress / Address: Rio de Janeiro (Brasilien) Rua Alice 308

,,fullAddress,streetNumber,street,city,state,country,postcode,houseNumber,buildingName
702,VictimCurrentAddress,"Kriftel, Bahnhofstr. 15",15,Bahnhofstr.,Kriftel,Niedersachsen,Deutschland,29653,,
1220,ApplicantCurrentAddress,"89-04 th Avenue, Jackson Heights L.I. N.Y./USA",89,04 Th Avenue,Jackson Heights,L.I.,USA,10071,Th,None
39,ApplicantCurrentAddress,"Nathania, Nordaustr. 34, Israel c/o Moskowitz ...",34,Nordaustr.,Israel,c/o,Moskowitz Mosche,1234,,
1266,ApplicantBirthPlace,Budapest/Ungarn,100,Vörösmarty tér,Budapest,Hungary,Hungary,1015,1,Körösváros
1292,ApplicantCurrentAddress,Rio de Janeiro (Brasilien) Rua Alice 308,308,Rua Alice,Rio de Janeiro,RJ,Brasilien,20062-000,0,null

In [ ]:
import gc
del model
gc.collect()
torch.cuda.empty_cache() # manually free up GPU memory; experiments show this helps

NameError: name 'model' is not defined

In [ ]:
model = LlamaAddressSegmentationModel("meta-llama/Llama-3.2-3B-Instruct", PROMPTS[0], JSONbjectParser())

In [27]:
test_model(model).dropna(how="all", axis=1).fillna("")

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Record ID: 426 / Field: ApplicantBirthPlace / Address: Alhausen b. Driburg

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Parsed response: {'streetNumber': None, 'street': 'Alhausen', 'city': 'Driburg', 'state': None, 'country': 'Germany', 'postcode': None, 'houseNumber': None, 'buildingName': 'Driburg', 'fullResponse': '{\n  "streetNumber": null,\n  "street": "Alhausen",\n  "city": "Driburg",\n  "state": null,\n  "country": "Germany",\n  "postcode": null,\n  "houseNumber": null,\n  "buildingName": "Driburg"\n}', 'fullAddress': 'Alhausen b. Driburg'}
Record ID: 237 / Field: ApplicantBirthPlace / Address: Galveston / USA

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Parsed response: {'streetNumber': None, 'street': None, 'city': 'Galveston', 'state': 'USA', 'country': 'USA', 'postcode': None, 'houseNumber': None, 'buildingName': None, 'fullResponse': '\n{\n  "streetNumber": null,\n  "street": null,\n  "city": "Galveston",\n  "state": "USA",\n  "country": "USA",\n  "postcode": null,\n  "houseNumber": null,\n  "buildingName": null\n}\n', 'fullAddress': 'Galveston / USA'}
Record ID: 5 / Field: VictimBirthPlace / Address: Esseck

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Parsed response: {'streetNumber': None, 'street': 'Esseck', 'city': None, 'state': None, 'country': None, 'postcode': None, 'houseNumber': None, 'buildingName': None, 'fullResponse': '{\n  "streetNumber": null,\n  "street": "Esseck",\n  "city": null,\n  "state": null,\n  "country": null,\n  "postcode": null,\n  "houseNumber": null,\n  "buildingName": null\n}', 'fullAddress': 'Esseck'}
Record ID: 1142 / Field: ApplicantCurrentAddress / Address: 43 W 93 St., c/o Mitchell, New York/USA

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Parsed response: {'streetNumber': '43', 'street': 'W 93 St.', 'city': 'New York', 'state': 'USA', 'country': 'USA', 'postcode': None, 'houseNumber': None, 'buildingName': None, 'fullResponse': '\n{\n  "streetNumber": "43",\n  "street": "W 93 St.",\n  "city": "New York",\n  "state": "USA",\n  "country": "USA",\n  "postcode": null,\n  "houseNumber": null,\n  "buildingName": null\n}\n', 'fullAddress': '43 W 93 St., c/o Mitchell, New York/USA'}
Record ID: 959 / Field: VictimDeathPlace / Address: Freiburg/Br.
Parsed response: {'streetNumber': None, 'street': 'Freiburg/Br.', 'city': 'Freiburg/Br.', 'state': None, 'country': 'Germany', 'postcode': None, 'houseNumber': None, 'buildingName': 'Freiburg/Br.', 'fullResponse': '{\n  "streetNumber": null,\n  "street": "Freiburg/Br.",\n  "city": "Freiburg/Br.",\n  "state": null,\n  "country": "Germany",\n  "postcode": null,\n  "houseNumber": null,\n  "buildingName": "Freiburg/Br."\n}', 'fullAddress': 'Freiburg/Br.'}

,,fullAddress,fullResponse,streetNumber,street,city,state,country,buildingName
426,ApplicantBirthPlace,Alhausen b. Driburg,"{\n ""streetNumber"": null,\n ""street"": ""Alhau...",,Alhausen,Driburg,,Germany,Driburg
237,ApplicantBirthPlace,Galveston / USA,"\n{\n ""streetNumber"": null,\n ""street"": null...",,,Galveston,USA,USA,
5,VictimBirthPlace,Esseck,"{\n ""streetNumber"": null,\n ""street"": ""Essec...",,Esseck,,,,
1142,ApplicantCurrentAddress,"43 W 93 St., c/o Mitchell, New York/USA","\n{\n ""streetNumber"": ""43"",\n ""street"": ""W 9...",43,W 93 St.,New York,USA,USA,
959,VictimDeathPlace,Freiburg/Br.,"{\n ""streetNumber"": null,\n ""street"": ""Freib...",,Freiburg/Br.,Freiburg/Br.,,Germany,Freiburg/Br.

In [44]:
del model
gc.collect()
torch.cuda.empty_cache()

In [41]:
model = LlamaAddressSegmentationModel("meta-llama/Llama-3.2-1B-Instruct", PROMPTS[1], JSONTuplesParser())
test_model(model).dropna(how="all", axis=1).fillna("")

Device set to use cuda:0
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Record ID: 403 / Field: ApplicantCurrentAddress / Address: Solingen, Bismarckstr. 90

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Parsed response: {'fullResponse': 'Here is the annotated address in JSON format:\n\n```json\n[\n  ["Solingen", "city"],\n  ["Bismarckstr.", "street"],\n  ["90", "streetNumber"],\n  [""] // no postcode\n  ["", "postcode"] // no houseNumber\n  ["", "buildingName"]\n]\n```\n\nExplanation:\n\n- `Solingen` is the city.\n- `Bismarckstr.` is the street, where `Bismarckstr.` is the abbreviation for the street name.\n- `90` is the streetNumber.\n- An empty string is the postcode.\n- An empty string is the houseNumber.\n- An empty string is the buildingName.', 'parseError': "JSONDecodeError: Expecting ',' delimiter: line 5 column 8 (char 89)", 'fullAddress': 'Solingen, Bismarckstr. 90'}
Record ID: 1252 / Field: ApplicantBirthPlace / Address: Göllheim/Pfalz

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Parsed response: {'fullResponse': 'I can annotate the components of the address "Göllheim/Pfalz".\n\nHere is the annotated address as a JSON list of [component, type] tuples:\n\n```\n[ ["Göllheim", "city"], ["Pfalz", "state"], ["Pfalz", "state"], ["Pfalz", "state"], ["Pfalz", "state"], ["Pfalz", "state"], ["Pfalz", "state"], ["Pfalz", "state"], ["Pfalz", "state"], ["Pfalz", "state"], ["Pfalz", "state"], ["Pfalz", "state"], ["Pfalz", "state"], ["Pfalz", "state"], ["Pfalz", "state"], ["Pfalz", "state"], ["Pfalz", "state"], ["Pfalz", "state"], ["Pfalz", "state"], ["Pfalz", "state"], ["Pfalz", "state"], ["Pfalz", "state"], ["Pfalz", "state"], ["Pfalz", "state"], ["Pfalz", "state"], ["Pfalz", "state"], ["Pfalz", "state"], ["P', 'parseError': 'JSONDecodeError: Expecting value: line 1 column 1 (char 0)', 'fullAddress': 'Göllheim/Pfalz'}
Record ID: 658 / Field: ApplicantCurrentAddress / Address: Gan-Odermheim, Goosmarkt 3

AttributeError: 'int' object has no attribute 'strip'