In [1]:
import place_lookup
lookup_table = place_lookup.PlaceLookupTable()

In [2]:
lookup_table.lookup("Germany")

,key,name,featureCode,isPreferred,source,sourceId,geonameId,distance
254425,Germany,Germany,A.PCLI,False,geonames,2921044,2921044,0
254415,German,German,A.PCLI,False,geonames,2921044,2921044,1
254416,Germani,Germani,A.PCLI,False,geonames,2921044,2921044,1
254417,Germania,Germania,A.PCLI,False,geonames,2921044,2921044,2
254419,Germanii,Germanii,A.PCLI,False,geonames,2921044,2921044,2
397755,Germant,Germant,P.PPL,False,geonames,3014367,3014367,1
397791,Gerand,Gerand,P.PPL,False,geonames,3014392,3014392,2
460248,Gervan,Gervan,P.PPL,False,geonames,2648626,2648626,2
569946,Kerman,Kerman,P.PPLA,True,geonames,128234,128234,2
569948,Kermano,Kermano,P.PPLA,False,geonames,128234,128234,2
575221,Kerman,Kerman,A.ADM2,False,geonames,449619,449619,2
22368,Gaiman,Gaiman,A.ADM2,False,geonames,3855282,3855282,3
70192,Garmen,Garmen,A.ADM2,False,geonames,730959,730959,3
70193,Gurmen,Gurmen,A.ADM2,False,geonames,730959,730959,3
147806,Gersau,Gersau,A.ADM2,False,geonames,6458810,6458810,3
569851,Kerman,Kerman,A.ADM1,False,geonames,128231,128231,2
569859,Kermana,Kermana,A.ADM1,False,geonames,128231,128231,2
569861,Kermano,Kermano,A.ADM1,False,geonames,128231,128231,2
569901,kermani,kermani,A.ADM1,False,geonames,128231,128231,2
1268854,vermant,vermant,A.ADM1,False,geonames,5242283,5242283,2
35405,Nerang,Nerang,P.PPLX,True,geonames,2155542,2155542,3
365090,Hermanni,Hermanni,P.PPLX,True,geonames,7521686,7521686,3
763698,Normandy,Normandy,P.PPLX,False,geonames,2139544,2139544,3
950097,Geylang,Geylang,P.PPLX,True,geonames,1880668,1880668,3
950100,geiran,geiran,P.PPLX,False,geonames,1880668,1880668,3
53599,seran,seran,A.ADM4,False,geonames,2786825,2786825,3
274892,Gera,Gera,A.ADM4,True,geonames,6549747,6549747,3
275538,granzy,granzy,A.ADM4,False,geonames,6550618,6550618,3
276838,Merane,Merane,A.ADM4,False,geonames,6550750,6550750,3
276844,merane,merane,A.ADM4,False,geonames,6550750,6550750,3
150298,Cermat,Cermat,A.ADM3,False,geonames,7287631,7287631,3
150300,Cermatt,Cermatt,A.ADM3,False,geonames,7287631,7287631,3
254664,Gera,Gera,A.ADM3,False,geonames,2921230,2921230,3
337775,Lerma,Lerma,A.ADM3,True,geonames,6356478,6356478,3
341975,Grana,Grana,A.ADM3,False,geonames,6357709,6357709,3

In [9]:
repr(lookup_table.code_hierarchy)

"[{'A.TERR', 'A.PCLI', 'A.PCL', 'A.PCLF', 'A.LTER', 'A.ZN', 'A.PCLD', 'A.PCLH', 'A.PCLS', 'A.PRSH', 'A.PCLIX'}, {'A.ADM1', 'A.ADM1H', 'A.ADMDH', 'A.ADMD'}, {'A.ADM2', 'A.ADM2H'}, {'A.ADM3H', 'A.ADM3'}, {'A.ADM4', 'A.ADM4H'}, {'A.ADM5'}, {'P.PPLA2', 'P.PPLA3', 'P.PPLA', 'P.PPLR', 'P.PPL', 'P.PPLA5', 'P.STLMT', 'P.PPLQ', 'P.PPLS', 'P.PPLG', 'P.PPLW', 'P.PPLC', 'P.PPLH', 'P.PPLL', 'P.PPLCH', 'P.PPLF', 'P.PPLA4'}, {'P.PPLX'}]"

In [4]:
lookup_table.lookup("Sachsen")

,key,name,featureCode,isPreferred,source,sourceId,geonameId,distance
230260,Sachsen,Sachsen,P.PPL,False,geonames,2842568,2842568,0
141743,Sachseln,Sachseln,P.PPL,True,geonames,2658894,2658894,1
1181225,Sachse,Sachse,P.PPL,True,geonames,4724564,4724564,1
143551,Lachen,Lachen,P.PPLA2,True,geonames,2660075,2660075,2
163935,Tachen,Tachen,P.PPLA2,False,geonames,1529167,1529167,2
230143,Sachsen,Sachsen,A.ADM1,False,geonames,2842566,2842566,0
66467,Sachel,Sachel,A.ADM1,False,geonames,6930713,6930713,2
230154,Saksen,Saksen,A.ADM1,False,geonames,2842566,2842566,2
230173,Sassen,Sassen,A.ADM1,False,geonames,2842566,2842566,2
230200,sakhsyn,sakhsyn,A.ADM1,False,geonames,2842566,2842566,2
282595,Aachen,Aachen,A.ADM4,True,geonames,6553047,6553047,2
288257,sai sen,sai sen,A.ADM4,False,geonames,6557376,6557376,2
53647,Schoten,Schoten,A.ADM4,True,geonames,2786964,2786964,3
56548,Machelen,Machelen,A.ADM4,True,geonames,2791953,2791953,3
60854,Esschen,Esschen,A.ADM4,False,geonames,2798616,2798616,3
684808,Sacheon,Sacheon,A.ADM2,False,geonames,8604736,8604736,2
684810,sacheon,sacheon,A.ADM2,False,geonames,8604736,8604736,2
163907,Tacheng,Tacheng,A.ADM2,False,geonames,1529166,1529166,3
171919,Sencsen,Sencsen,A.ADM2,False,geonames,1795563,1795563,3
171941,shensen,shensen,A.ADM2,False,geonames,1795563,1795563,3
147266,Saatlen,Saatlen,P.PPLX,False,geonames,6295490,6295490,3
635924,da sen,da sen,P.PPLX,False,geonames,1854109,1854109,3
148758,Bache,Bache,A.ADM3,False,geonames,7285225,7285225,3
149254,hao sen,hao sen,A.ADM3,False,geonames,7286037,7286037,3
185338,Pa Hsien,Pa Hsien,A.ADM3,False,geonames,1816835,1816835,3
191577,Acheng,Acheng,A.ADM3,True,geonames,2038678,2038678,3
337133,Sal'en,Sal'en,A.ADM3,False,geonames,6356215,6356215,3
72150,Bachrein,Bachrein,A.PCLI,False,geonames,290291,290291,3
72220,bahren,bahren,A.PCLI,False,geonames,290291,290291,3
681397,Chosen,Chosen,A.PCLI,False,geonames,1835841,1835841,3
681586,Tchosen,Tchosen,A.PCLI,False,geonames,1835841,1835841,3
936962,Xay-sen,Xay-sen,A.PCLI,False,geonames,241170,241170,3

In [5]:
lookup_table.lookup("Berlin")

,key,name,featureCode,isPreferred,source,sourceId,geonameId,distance
264743,Berlin,Berlin,P.PPLC,True,geonames,2950159,2950159,0
969434,Berlin,Berlin,P.PPL,False,geonames,3587266,3587266,0
1131580,Berlin,Berlin,P.PPL,True,geonames,4348460,4348460,0
1131734,Berlin,Berlin,P.PPL,False,geonames,4349706,4349706,0
1152421,Berlin,Berlin,P.PPL,True,geonames,4500771,4500771,0
273004,Berlin,Berlin,A.ADM4,True,geonames,6547539,6547539,0
273005,Berlino,Berlino,A.ADM4,False,geonames,6547539,6547539,1
434853,Bernin,Bernin,A.ADM4,True,geonames,6448727,6448727,1
436015,Barlin,Barlin,A.ADM4,True,geonames,6450284,6450284,1
51448,Welin,Welin,A.ADM4,False,geonames,2783863,2783863,2
264655,Berlin,Berlin,A.ADM1,False,geonames,2950157,2950157,0
264695,berlin,berlin,A.ADM1,False,geonames,2950157,2950157,0
264644,Barlin,Barlin,A.ADM1,False,geonames,2950157,2950157,1
264646,Beirlin,Beirlin,A.ADM1,False,geonames,2950157,2950157,1
264651,Berlien,Berlien,A.ADM1,False,geonames,2950157,2950157,1
191999,Beilin,Beilin,A.ADM3,False,geonames,6599410,6599410,1
623866,Merlin,Merlin,A.ADM3,False,geonames,6543690,6543690,1
1044379,Erlin,Erlin,A.ADM3,False,geonames,1676913,1676913,1
148744,Bern,Bern,A.ADM3,False,geonames,7285212,7285212,2
186964,Beilun,Beilun,A.ADM3,False,geonames,1922900,1922900,2
1315281,Berli,Berli,A.ADM2,False,geonames,5688266,5688266,1
102463,Betin,Betin,A.ADM2,False,geonames,6321168,6321168,2
102465,bechin,bechin,A.ADM2,False,geonames,6321168,6321168,2
150462,Bernina,Bernina,A.ADM2,False,geonames,11611656,11611656,2
204558,Belen,Belen,A.ADM2,False,geonames,3689007,3689007,2
443318,Bersi,Bersi,P.PPLX,False,geonames,6545266,6545266,2
790930,Belen,Belen,P.PPLX,True,geonames,3827811,3827811,2
33204,Belair,Belair,P.PPLX,True,geonames,2076842,2076842,3
36749,Erina,Erina,P.PPLX,True,geonames,2167263,2167263,3
37584,Bulli,Bulli,P.PPLX,True,geonames,2173445,2173445,3
72182,Barein,Barein,A.PCLI,False,geonames,290291,290291,2
72206,ba lin,ba lin,A.PCLI,False,geonames,290291,290291,2
74532,Beinin,Beinin,A.PCLI,False,geonames,2395170,2395170,2
74538,Benin,Benin,A.PCLI,False,geonames,2395170,2395170,2
74554,Bènin,Bènin,A.PCLI,False,geonames,2395170,2395170,2

In [6]:
lookup_table.lookup("Sachsen", feature_codes="State")

,key,name,featureCode,isPreferred,source,sourceId,geonameId,distance
230143,Sachsen,Sachsen,A.ADM1,False,geonames,2842566,2842566,0
66467,Sachel,Sachel,A.ADM1,False,geonames,6930713,6930713,2
230154,Saksen,Saksen,A.ADM1,False,geonames,2842566,2842566,2
230173,Sassen,Sassen,A.ADM1,False,geonames,2842566,2842566,2
230200,sakhsyn,sakhsyn,A.ADM1,False,geonames,2842566,2842566,2
282595,Aachen,Aachen,A.ADM4,True,geonames,6553047,6553047,2
288257,sai sen,sai sen,A.ADM4,False,geonames,6557376,6557376,2
53647,Schoten,Schoten,A.ADM4,True,geonames,2786964,2786964,3
56548,Machelen,Machelen,A.ADM4,True,geonames,2791953,2791953,3
60854,Esschen,Esschen,A.ADM4,False,geonames,2798616,2798616,3
684808,Sacheon,Sacheon,A.ADM2,False,geonames,8604736,8604736,2
684810,sacheon,sacheon,A.ADM2,False,geonames,8604736,8604736,2
163907,Tacheng,Tacheng,A.ADM2,False,geonames,1529166,1529166,3
171919,Sencsen,Sencsen,A.ADM2,False,geonames,1795563,1795563,3
171941,shensen,shensen,A.ADM2,False,geonames,1795563,1795563,3
148758,Bache,Bache,A.ADM3,False,geonames,7285225,7285225,3
149254,hao sen,hao sen,A.ADM3,False,geonames,7286037,7286037,3
185338,Pa Hsien,Pa Hsien,A.ADM3,False,geonames,1816835,1816835,3
191577,Acheng,Acheng,A.ADM3,True,geonames,2038678,2038678,3
337133,Sal'en,Sal'en,A.ADM3,False,geonames,6356215,6356215,3

In [7]:

lookup_table.lookup("Lisboa")

,key,name,featureCode,isPreferred,source,sourceId,geonameId,distance
849583,Lisboa,Lisboa,P.PPLC,False,geonames,2267057,2267057,0
849584,Lisbon,Lisbon,P.PPLC,True,geonames,2267057,2267057,1
849585,Lisbona,Lisbona,P.PPLC,False,geonames,2267057,2267057,1
849593,Lizboa,Lizboa,P.PPLC,False,geonames,2267057,2267057,1
1155335,Lisbon,Lisbon,P.PPL,True,geonames,4516749,4516749,1
852212,Lisboa,Lisboa,A.ADM2,False,geonames,6458923,6458923,0
852213,Lisbon,Lisbon,A.ADM2,True,geonames,6458923,6458923,1
200662,Pisba,Pisba,A.ADM2,True,geonames,3672144,3672144,2
479683,Lesbos,Lesbos,A.ADM2,True,geonames,258465,258465,2
631366,li bo,li bo,A.ADM2,False,geonames,1850038,1850038,2
849533,Lisboa,Lisboa,A.ADM1,False,geonames,2267056,2267056,0
849535,Lisbon,Lisbon,A.ADM1,False,geonames,2267056,2267056,1
849540,Lisbona,Lisbona,A.ADM1,False,geonames,2267056,2267056,1
849531,Lisabon,Lisabon,A.ADM1,False,geonames,2267056,2267056,2
849547,Lizbona,Lizbona,A.ADM1,False,geonames,2267056,2267056,2
1078614,Lisok,Lisok,P.PPLX,True,geonames,13561775,13561775,2
35996,Lisarow,Lisarow,P.PPLX,True,geonames,2160070,2160070,3
87813,LIB,LIB,P.PPLX,False,geonames,3458611,3458611,3
118555,Limao,Limao,P.PPLX,False,geonames,7614952,7614952,3
208277,Vibora,Vibora,P.PPLX,False,geonames,3550209,3550209,3
57093,Limbor,Limbor,A.ADM4,False,geonames,2792349,2792349,2
56986,Lissin,Lissin,A.ADM4,False,geonames,2792333,2792333,3
57095,Limbur,Limbur,A.ADM4,False,geonames,2792349,2792349,3
57100,Limbôr,Limbôr,A.ADM4,False,geonames,2792349,2792349,3
57176,Lira,Lira,A.ADM4,False,geonames,2792406,2792406,3
341511,Libia,Libia,A.ADM3,False,geonames,6357610,6357610,2
485564,Lesbos,Lesbos,A.ADM3,False,geonames,8133755,8133755,2
796872,Libog,Libog,A.ADM3,False,geonames,1687749,1687749,2
801373,Libon,Libon,A.ADM3,True,geonames,1706612,1706612,2
838118,Liskow,Liskow,A.ADM3,False,geonames,7532499,7532499,2
690880,Liba,Liba,A.PCLI,False,geonames,272103,272103,2
690881,Libaa,Libaa,A.PCLI,False,geonames,272103,272103,2
698502,litbha,litbha,A.PCLI,False,geonames,597427,597427,2
706486,Libbia,Libbia,A.PCLI,False,geonames,2215636,2215636,2
706489,Libia,Libia,A.PCLI,False,geonames,2215636,2215636,2

In [8]:
lookup_table.lookup("Lisboa", feature_codes="District")

,key,name,featureCode,isPreferred,source,sourceId,geonameId,distance
852212,Lisboa,Lisboa,A.ADM2,False,geonames,6458923,6458923,0
852213,Lisbon,Lisbon,A.ADM2,True,geonames,6458923,6458923,1
200662,Pisba,Pisba,A.ADM2,True,geonames,3672144,3672144,2
479683,Lesbos,Lesbos,A.ADM2,True,geonames,258465,258465,2
631366,li bo,li bo,A.ADM2,False,geonames,1850038,1850038,2
849533,Lisboa,Lisboa,A.ADM1,False,geonames,2267056,2267056,0
849535,Lisbon,Lisbon,A.ADM1,False,geonames,2267056,2267056,1
849540,Lisbona,Lisbona,A.ADM1,False,geonames,2267056,2267056,1
849531,Lisabon,Lisabon,A.ADM1,False,geonames,2267056,2267056,2
849547,Lizbona,Lizbona,A.ADM1,False,geonames,2267056,2267056,2
57093,Limbor,Limbor,A.ADM4,False,geonames,2792349,2792349,2
56986,Lissin,Lissin,A.ADM4,False,geonames,2792333,2792333,3
57095,Limbur,Limbur,A.ADM4,False,geonames,2792349,2792349,3
57100,Limbôr,Limbôr,A.ADM4,False,geonames,2792349,2792349,3
57176,Lira,Lira,A.ADM4,False,geonames,2792406,2792406,3
341511,Libia,Libia,A.ADM3,False,geonames,6357610,6357610,2
485564,Lesbos,Lesbos,A.ADM3,False,geonames,8133755,8133755,2
796872,Libog,Libog,A.ADM3,False,geonames,1687749,1687749,2
801373,Libon,Libon,A.ADM3,True,geonames,1706612,1706612,2
838118,Liskow,Liskow,A.ADM3,False,geonames,7532499,7532499,2